Repository kubernetes-sigs/ingate, pull requests merged in 2024-12, with the labels that each got.

#1 Docs: Update `README.md` & `RELEASE.md`.
  README.md
  RELEASE.md
Labels: cncf-cla: yes, approved, size/M, lgtm

#2 Owners: Add SIG Network leads as approvers.
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, lgtm, size/S

#3 Docs: Update `SECURITY_CONTACTS`.
  SECURITY_CONTACTS
Labels: cncf-cla: yes, approved, size/XS

#6 Docs: Add Gateway API URL.
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#7 Docs: Some minor improvements.
  README.md
  RELEASE.md
  hack/boilerplate/boilerplate.yaml.txt
Labels: cncf-cla: yes, approved, size/XS

#8 hack: Fix incorrect bash variable
  hack/verify-boilerplate.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#9 Docs: Remove trailing whitespaces.
  CONTRIBUTING.md
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, lgtm, size/XS

#10 Repository: Update owners.
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, approved, size/M
