Repository kubernetes-sigs/ingate, pull requests merged in 2025-03, with the labels that each got.

#19 update contribute and readme
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, approved, size/S

#21 Contributing: Fix typo.
  CONTRIBUTING.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#20 Repository: Add documentation.
  .github/workflows/docs.yaml
  OWNERS_ALIASES
  docs/OWNERS
  docs/contributing.md
  docs/faq.md
  docs/index.md
  mkdocs.yml
Labels: cncf-cla: yes, approved, size/M, lgtm
